### ISSUE TITLE
Allow reverse queries on app links

### ISSUE THREAD

**Issue by manu0466** [desmos-labs/desmos#781] opened 2022-03-17 16:20 UTC
## Bug description
The [app-link gRPC](https://github.com/desmos-labs/desmos/blob/8140a5c2460dca25a6908d6f10ad85c5becda054/x/profiles/keeper/grpc_query.go#L126) don't correctly handle the case on which the user perform a request with application, username but without providing the user address.  

## Expected behavior
In case that an user perform the request without the address but with application or username the request should fail and not return all the app-links

**Comment by RiccardoM** [comment] 2022-03-21 09:06
This is actually the intended behavior for this query: if the client does not provide a valid `user` address, then neither the `application` nor the `username` field will be used to query the links. I will change this to make sure we implement the reserve query by application + username in the next release

**Comment by RiccardoM** [comment] 2022-03-21 12:51
Actually, closing this as a duplicate of #777

**Closed by RiccardoM** 2022-03-21 12:51 UTC
Labels: kind/new-feature
